spring:
  application:
    name: springtest
  mvc:
    servlet:
      load-on-startup: 1
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          group: springtest
          consumer:
            recoveryInterval: 10000
    database: 12
    pool:
      max-active: 5000
      max-wait: 10000
      max-idle: 100
      min-idle: 10
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-wait: 30000
    validation-query: select 1
    validation-interval: 10000
    validation-query-timeout: 5000
    max-active: 20
    max-idle: 20
    maximum-pool-size: 20
    remove-abandoned: true
    test-while-idle: true
    min-idle: 0
    num-tests-per-eviction-run: 3
server:
  port: ${PORT:7001}
management:
  security:
    enabled: false