spring:
  application:
    name: springtest
  mvc:
    servlet:
      load-on-startup: 1
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          group: springtest
          consumer:
            recoveryInterval: 10000
server:
  port: ${PORT:7001}
management:
  security:
    enabled: false